# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/trlte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/trlte/proprietary/blobs/spr/bin/efsks:system/blobs/spr/bin/efsks \
    vendor/samsung/trlte/proprietary/blobs/spr/bin/ks:system/blobs/spr/bin/ks \
    vendor/samsung/trlte/proprietary/blobs/spr/bin/mdm_helper:system/blobs/spr/bin/mdm_helper \
    vendor/samsung/trlte/proprietary/blobs/spr/bin/mdm_helper_proxy:system/blobs/spr/bin/mdm_helper_proxy \
    vendor/samsung/trlte/proprietary/blobs/spr/bin/qcks:system/blobs/spr/bin/qcks \
    vendor/samsung/trlte/proprietary/blobs/spr/bin/qmuxd:system/blobs/spr/bin/qmuxd \
    vendor/samsung/trlte/proprietary/blobs/spr/bin/rild:system/blobs/spr/bin/rild \
    vendor/samsung/trlte/proprietary/blobs/spr/bin/rmnetcli:system/blobs/spr/bin/rmnetcli \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libbt-aptX-ARM-4.2.2.so:system/blobs/spr/lib/libbt-aptX-ARM-4.2.2.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libbt-codec_aptx.so:system/blobs/spr/lib/libbt-codec_aptx.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libbt-codec_sshd.so:system/blobs/spr/lib/libbt-codec_sshd.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libbt-iopdb.so:system/blobs/spr/lib/libbt-iopdb.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libbt-iopdb_mod.so:system/blobs/spr/lib/libbt-iopdb_mod.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libbt-vendor.so:system/blobs/spr/lib/libbt-vendor.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libcfiril.so:system/blobs/spr/lib/libcfiril.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libloc_api_v02.so:system/blobs/spr/lib/libloc_api_v02.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libreference-ril.so:system/blobs/spr/lib/libreference-ril.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libril.so:system/blobs/spr/lib/libril.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/librilswitch.so:system/blobs/spr/lib/librilswitch.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/librmnetctl.so:system/blobs/spr/lib/librmnetctl.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libsec-ril.so:system/blobs/spr/lib/libsec-ril.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libsecnativefeature.so:system/blobs/spr/lib/libsecnativefeature.so \
    vendor/samsung/trlte/proprietary/blobs/spr/lib/libsecril-client.so:system/blobs/spr/lib/libsecril-client.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/firmware/BT_FW_BCM4358A1_001.002.005.0032.0066.hcd:system/blobs/spr/vendor/firmware/BT_FW_BCM4358A1_001.002.005.0032.0066.hcd \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/firmware/bcm43569.hcd:system/blobs/spr/vendor/firmware/bcm43569.hcd \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/firmware/bcm43569A0.hcd:system/blobs/spr/vendor/firmware/bcm43569A0.hcd \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/firmware/bcm43569A1.hcd:system/blobs/spr/vendor/firmware/bcm43569A1.hcd \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/firmware/sec_s3fwrn5_firmware.bin:system/blobs/spr/vendor/firmware/sec_s3fwrn5_firmware.bin \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/hw/flp.default.so:system/blobs/spr/vendor/lib/hw/flp.default.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libalarmservice_jni.so:system/blobs/spr/vendor/lib/libalarmservice_jni.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libconfigdb.so:system/blobs/spr/vendor/lib/libconfigdb.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libdiag.so:system/blobs/spr/vendor/lib/libdiag.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libdsutils.so:system/blobs/spr/vendor/lib/libdsutils.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libgeofence.so:system/blobs/spr/vendor/lib/libgeofence.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libidl.so:system/blobs/spr/vendor/lib/libidl.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libizat_core.so:system/blobs/spr/vendor/lib/libizat_core.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/liblbs_core.so:system/blobs/spr/vendor/lib/liblbs_core.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/liblocationservice.so:system/blobs/spr/vendor/lib/liblocationservice.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libmdmdetect.so:system/blobs/spr/vendor/lib/libmdmdetect.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libqcci_legacy.so:system/blobs/spr/vendor/lib/libqcci_legacy.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libqmi.so:system/blobs/spr/vendor/lib/libqmi.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libqmi_cci.so:system/blobs/spr/vendor/lib/libqmi_cci.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libqmi_client_qmux.so:system/blobs/spr/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libqmi_common_so.so:system/blobs/spr/vendor/lib/libqmi_common_so.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libqmi_csi.so:system/blobs/spr/vendor/lib/libqmi_csi.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libqmi_encdec.so:system/blobs/spr/vendor/lib/libqmi_encdec.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libqmiservices.so:system/blobs/spr/vendor/lib/libqmiservices.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libril-qcril-hook-oem.so:system/blobs/spr/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libtime_genoff.so:system/blobs/spr/vendor/lib/libtime_genoff.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libulp2.so:system/blobs/spr/vendor/lib/libulp2.so \
    vendor/samsung/trlte/proprietary/blobs/spr/vendor/lib/libxml.so:system/blobs/spr/vendor/lib/libxml.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/bin/efsks:system/blobs/tmo/bin/efsks \
    vendor/samsung/trlte/proprietary/blobs/tmo/bin/ks:system/blobs/tmo/bin/ks \
    vendor/samsung/trlte/proprietary/blobs/tmo/bin/mdm_helper:system/blobs/tmo/bin/mdm_helper \
    vendor/samsung/trlte/proprietary/blobs/tmo/bin/mdm_helper_proxy:system/blobs/tmo/bin/mdm_helper_proxy \
    vendor/samsung/trlte/proprietary/blobs/tmo/bin/qcks:system/blobs/tmo/bin/qcks \
    vendor/samsung/trlte/proprietary/blobs/tmo/bin/qmuxd:system/blobs/tmo/bin/qmuxd \
    vendor/samsung/trlte/proprietary/blobs/tmo/bin/rild:system/blobs/tmo/bin/rild \
    vendor/samsung/trlte/proprietary/blobs/tmo/bin/rmnetcli:system/blobs/tmo/bin/rmnetcli \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libagc_max.so:system/blobs/tmo/lib/libagc_max.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libbt-aptX-ARM-4.2.2.so:system/blobs/tmo/lib/libbt-aptX-ARM-4.2.2.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libbt-codec_aptx.so:system/blobs/tmo/lib/libbt-codec_aptx.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libbt-codec_sshd.so:system/blobs/tmo/lib/libbt-codec_sshd.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libbt-iopdb.so:system/blobs/tmo/lib/libbt-iopdb.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libbt-iopdb_mod.so:system/blobs/tmo/lib/libbt-iopdb_mod.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libbt-vendor.so:system/blobs/tmo/lib/libbt-vendor.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libcfiril.so:system/blobs/tmo/lib/libcfiril.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libcontrolcsc.so:system/blobs/tmo/lib/libcontrolcsc.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libedmnativehelper.so:system/blobs/tmo/lib/libedmnativehelper.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libjpegdhw.so:system/blobs/tmo/lib/libjpegdhw.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libjpegehw.so:system/blobs/tmo/lib/libjpegehw.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libloc_api_v02.so:system/blobs/tmo/lib/libloc_api_v02.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libprotobuf-cpp-full.so:system/blobs/tmo/lib/libprotobuf-cpp-full.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libqdutils.so:system/blobs/tmo/lib/libqdutils.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libqservice.so:system/blobs/tmo/lib/libqservice.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libreference-ril.so:system/blobs/tmo/lib/libreference-ril.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libril.so:system/blobs/tmo/lib/libril.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/librilswitch.so:system/blobs/tmo/lib/librilswitch.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/librilutils.so:system/blobs/tmo/lib/librilutils.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/librmnetctl.so:system/blobs/tmo/lib/librmnetctl.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libsec-ril.so:system/blobs/tmo/lib/libsec-ril.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libsecnativefeature.so:system/blobs/tmo/lib/libsecnativefeature.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libsecril-client.so:system/blobs/tmo/lib/libsecril-client.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libshdace.so:system/blobs/tmo/lib/libshdace.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/lib/libtinyxml.so:system/blobs/tmo/lib/libtinyxml.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/hw/flp.default.so:system/blobs/tmo/vendor/lib/hw/flp.default.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libconfigdb.so:system/blobs/tmo/vendor/lib/libconfigdb.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libdataitems.so:system/blobs/tmo/vendor/lib/libdataitems.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libdiag.so:system/blobs/tmo/vendor/lib/libdiag.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libdsutils.so:system/blobs/tmo/vendor/lib/libdsutils.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libflp.so:system/blobs/tmo/vendor/lib/libflp.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libgeofence.so:system/blobs/tmo/vendor/lib/libgeofence.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libidl.so:system/blobs/tmo/vendor/lib/libidl.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libizat_core.so:system/blobs/tmo/vendor/lib/libizat_core.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/liblbs_core.so:system/blobs/tmo/vendor/lib/liblbs_core.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/liblocationservice.so:system/blobs/tmo/vendor/lib/liblocationservice.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/liblowi_client.so:system/blobs/tmo/vendor/lib/liblowi_client.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libmdmdetect.so:system/blobs/tmo/vendor/lib/libmdmdetect.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libnetmgr.so:system/blobs/tmo/vendor/lib/libnetmgr.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libqcci_legacy.so:system/blobs/tmo/vendor/lib/libqcci_legacy.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libqmi.so:system/blobs/tmo/vendor/lib/libqmi.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libqmi_cci.so:system/blobs/tmo/vendor/lib/libqmi_cci.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libqmi_client_qmux.so:system/blobs/tmo/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libqmi_common_so.so:system/blobs/tmo/vendor/lib/libqmi_common_so.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libqmi_csi.so:system/blobs/tmo/vendor/lib/libqmi_csi.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libqmi_encdec.so:system/blobs/tmo/vendor/lib/libqmi_encdec.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libqmiservices.so:system/blobs/tmo/vendor/lib/libqmiservices.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libril-qcril-hook-oem.so:system/blobs/tmo/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/trlte/proprietary/blobs/tmo/vendor/lib/libulp2.so:system/blobs/tmo/vendor/lib/libulp2.so \
    vendor/samsung/trlte/proprietary/blobs/xx/bin/efsks:system/blobs/xx/bin/efsks \
    vendor/samsung/trlte/proprietary/blobs/xx/bin/ks:system/blobs/xx/bin/ks \
    vendor/samsung/trlte/proprietary/blobs/xx/bin/mdm_helper:system/blobs/xx/bin/mdm_helper \
    vendor/samsung/trlte/proprietary/blobs/xx/bin/mdm_helper_proxy:system/blobs/xx/bin/mdm_helper_proxy \
    vendor/samsung/trlte/proprietary/blobs/xx/bin/qcks:system/blobs/xx/bin/qcks \
    vendor/samsung/trlte/proprietary/blobs/xx/bin/qmuxd:system/blobs/xx/bin/qmuxd \
    vendor/samsung/trlte/proprietary/blobs/xx/bin/rild:system/blobs/xx/bin/rild \
    vendor/samsung/trlte/proprietary/blobs/xx/bin/rmnetcli:system/blobs/xx/bin/rmnetcli \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libagc_max.so:system/blobs/xx/lib/libagc_max.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libbt-aptX-ARM-4.2.2.so:system/blobs/xx/lib/libbt-aptX-ARM-4.2.2.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libbt-codec_aptx.so:system/blobs/xx/lib/libbt-codec_aptx.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libbt-codec_sshd.so:system/blobs/xx/lib/libbt-codec_sshd.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libbt-iopdb.so:system/blobs/xx/lib/libbt-iopdb.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libbt-iopdb_mod.so:system/blobs/xx/lib/libbt-iopdb_mod.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libbt-vendor.so:system/blobs/xx/lib/libbt-vendor.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libedmnativehelper.so:system/blobs/xx/lib/libedmnativehelper.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libjpegdhw.so:system/blobs/xx/lib/libjpegdhw.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libjpegehw.so:system/blobs/xx/lib/libjpegehw.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libprotobuf-cpp-full.so:system/blobs/xx/lib/libprotobuf-cpp-full.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libqdutils.so:system/blobs/xx/lib/libqdutils.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libqservice.so:system/blobs/xx/lib/libqservice.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libreference-ril.so:system/blobs/xx/lib/libreference-ril.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libril.so:system/blobs/xx/lib/libril.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/librmnetctl.so:system/blobs/xx/lib/librmnetctl.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libsec-ril.so:system/blobs/xx/lib/libsec-ril.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libsecnativefeature.so:system/blobs/xx/lib/libsecnativefeature.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libsecril-client.so:system/blobs/xx/lib/libsecril-client.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libshdace.so:system/blobs/xx/lib/libshdace.so \
    vendor/samsung/trlte/proprietary/blobs/xx/lib/libtinyxml.so:system/blobs/xx/lib/libtinyxml.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libconfigdb.so:system/blobs/xx/vendor/lib/libconfigdb.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libdataitems.so:system/blobs/xx/vendor/lib/libdataitems.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libdiag.so:system/blobs/xx/vendor/lib/libdiag.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libdsutils.so:system/blobs/xx/vendor/lib/libdsutils.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libflp.so:system/blobs/xx/vendor/lib/libflp.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libidl.so:system/blobs/xx/vendor/lib/libidl.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/liblowi_client.so:system/blobs/xx/vendor/lib/liblowi_client.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libmdmdetect.so:system/blobs/xx/vendor/lib/libmdmdetect.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libnetmgr.so:system/blobs/xx/vendor/lib/libnetmgr.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libperipheral_client.so:system/blobs/xx/vendor/lib/libperipheral_client.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libqcci_legacy.so:system/blobs/xx/vendor/lib/libqcci_legacy.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libqmi.so:system/blobs/xx/vendor/lib/libqmi.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libqmi_cci.so:system/blobs/xx/vendor/lib/libqmi_cci.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libqmi_client_qmux.so:system/blobs/xx/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libqmi_common_so.so:system/blobs/xx/vendor/lib/libqmi_common_so.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libqmi_csi.so:system/blobs/xx/vendor/lib/libqmi_csi.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libqmi_encdec.so:system/blobs/xx/vendor/lib/libqmi_encdec.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libqmiservices.so:system/blobs/xx/vendor/lib/libqmiservices.so \
    vendor/samsung/trlte/proprietary/blobs/xx/vendor/lib/libril-qcril-hook-oem.so:system/blobs/xx/vendor/lib/libril-qcril-hook-oem.so
